renderMarketBenchmark
renderMarketComparison
renderROIMarketComparison
renderRevenueForecast
renderOccupancySensitivity
export {
renderMarketBenchmark,
renderMarketComparison,
renderROIMarketComparison,
renderRevenueForecast,
renderOccupancySensitivity
}
