import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../js/dashboard.js',import.meta.url),'utf8');
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
const a=source.indexOf('window.loadCurrentPropertyTouristTax =');
const tax=source.slice(a,source.indexOf('const getPricingMarket',a));
function taxHarness(){const pending=[];const ctx={window:{},isDemo:()=>false,canUseFirestorePMS:()=>true,db:{},doc:(_db,_col,id)=>id,getDoc:id=>{const d=deferred();pending.push({id,...d});return d.promise;}};vm.createContext(ctx);vm.runInContext(tax,ctx);return {ctx,pending};}
function snapshot(id){return {exists:()=>true,data:()=>({name:id,touristTaxConfig:{rate:id}})};}
test('slower property response cannot replace the most recent property and tax rule',async()=>{const h=taxHarness();const first=h.ctx.window.loadCurrentPropertyTouristTax('first');const second=h.ctx.window.loadCurrentPropertyTouristTax('second');h.pending[1].resolve(snapshot('second'));await second;h.pending[0].resolve(snapshot('first'));await first;assert.equal(h.ctx.window.currentPropertyId,'second');assert.equal(h.ctx.window.currentPropertyTouristTaxConfig.rate,'second');});
test('closing booking while property data loads discards the response',async()=>{const h=taxHarness();const p=h.ctx.window.loadCurrentPropertyTouristTax('first');h.ctx.window.rbBookingViewVersion=1;h.pending[0].resolve(snapshot('first'));await p;assert.equal(h.ctx.window.currentPropertyId,undefined);});
const detailsStart=source.indexOf('window.showBookingDetails = async');
const detailsPrefix=source.slice(detailsStart,source.indexOf('    const bookingProperty =',detailsStart))+'\nwindow.renderedBooking=booking.id;};';
function detailsHarness(){const pending=[],options=[];const form={style:{display:'flex'},querySelector:()=>null};const w={loadCurrentPropertyTouristTax:()=>{const d=deferred();pending.push(d);return d.promise;},loadBookingPropertyOptions:()=>{const d=deferred();options.push(d);return d.promise;},t:x=>x};const ctx={window:w,document:{getElementById:()=>form},renderBookingTaskTracking:()=>{},dashboardError:()=>{}};vm.createContext(ctx);vm.runInContext(detailsPrefix,ctx);return {w,form,pending,options};}
test('latest booking wins when first property load finishes last',async()=>{const h=detailsHarness();const first=h.w.showBookingDetails({id:'one',propertyId:'p1'});const second=h.w.showBookingDetails({id:'two',propertyId:'p2'});h.pending[1].resolve();await new Promise(setImmediate);h.options[0].resolve();await second;h.pending[0].resolve();await first;assert.equal(h.w.renderedBooking,'two');assert.equal(h.w.currentSelectedBooking.id,'two');});
test('stale booking cannot fill fields after a delayed property selector load',async()=>{const h=detailsHarness();const first=h.w.showBookingDetails({id:'one'});h.pending[0].resolve();await new Promise(setImmediate);const second=h.w.showBookingDetails({id:'two'});h.pending[1].resolve();await new Promise(setImmediate);h.options[1].resolve();await second;h.options[0].resolve();await first;assert.equal(h.w.renderedBooking,'two');});
test('closing while booking opens keeps form hidden and discards rendering',async()=>{const h=detailsHarness();const p=h.w.showBookingDetails({id:'one'});h.w.rbBookingViewVersion++;h.pending[0].resolve();await p;assert.equal(h.form.style.display,'none');assert.equal(h.w.renderedBooking,undefined);});
test('reopening bookings repeatedly binds each field handler only once',()=>{const start=source.indexOf('  // Ricollega gli eventi del form');const end=source.indexOf('  },100);',start)+'  },100);'.length;const callbacks=[],elements=new Map();const ctx={window:{updateBookingGuestRegistration:()=>{},updateBookingCleaning:()=>{},updateBookingGuestIssue:()=>{}},setTimeout:fn=>callbacks.push(fn),updateBookingTotal:()=>{},document:{getElementById:id=>{if(!elements.has(id))elements.set(id,{dataset:{},listeners:[],addEventListener(type,fn){this.listeners.push({type,fn});}});return elements.get(id);}}};vm.createContext(ctx);const bind=()=>vm.runInContext(source.slice(start,end),ctx);bind();bind();bind();callbacks.forEach(fn=>fn());for(const id of ['booking-checkout','booking-guests','booking-taxable-guests','booking-cleaning-date'])assert.equal(elements.get(id).listeners.length,1,id);});
