import test from 'node:test';
import assert from 'node:assert/strict';
import {createEmailVerification} from '../js/pms-email-verification.js';
function fixture(){let time=0,sends=0,refreshes=0;const user={uid:'owner',emailVerified:false,getIdToken:async force=>{assert.equal(force,true);refreshes++;}};let current=user;const controller=createEmailVerification({getUser:()=>current,reload:async()=>{},send:async value=>{assert.equal(value,user);sends++;},now:()=>time});return {user,controller,setTime:v=>time=v,setUser:v=>current=v,counts:()=>({sends,refreshes})};}
test('verification email goes to the authenticated user and throttles repeats',async()=>{const f=fixture();assert.equal(await f.controller.send(),'sent');await assert.rejects(f.controller.send(),/cooldown/);f.setTime(60000);await f.controller.send();assert.equal(f.counts().sends,2);});
test('checking refreshes the token but never invents verified state',async()=>{const f=fixture();assert.equal(await f.controller.check(),'unverified');f.user.emailVerified=true;assert.equal(await f.controller.check(),'verified');assert.equal(f.counts().refreshes,2);});
test('verified users refresh their token without another email',async()=>{const f=fixture();f.user.emailVerified=true;assert.equal(await f.controller.send(),'verified');assert.deepEqual(f.counts(),{sends:0,refreshes:1});});
test('signed out and demo users cannot send',async()=>{const f=fixture();f.setUser(null);await assert.rejects(f.controller.send(),/signed_in_required/);f.setUser({uid:'demo-user'});await assert.rejects(f.controller.check(),/signed_in_required/);});
test('account change during reload aborts sending',async()=>{let current={uid:'a'};let sends=0;const controller=createEmailVerification({getUser:()=>current,reload:async()=>{current={uid:'b'};},send:async()=>sends++});await assert.rejects(controller.send(),/account_changed/);assert.equal(sends,0);});
test('provider errors allow retry and parallel sends are blocked',async()=>{let release;let fail=true;const user={uid:'a',emailVerified:false};const c=createEmailVerification({getUser:()=>user,reload:async()=>{},send:async()=>{if(fail)throw Error('provider');await new Promise(r=>release=r);}});await assert.rejects(c.send(),/provider/);fail=false;const pending=c.send();await new Promise(r=>setImmediate(r));await assert.rejects(c.send(),/busy/);release();assert.equal(await pending,'sent');});
