import test from 'node:test';
import assert from 'node:assert/strict';
import {MemoryFirestore} from './helpers/pms-memory-firestore.js';
import {queueDailyReminders} from '../lib/pms-reminders.js';
import {drainTaskNotifications} from '../lib/pms-notification-queue.js';
const now=Date.parse('2026-10-07T07:00:00Z');
function setup(size=20){
 const seed={};
 for(let i=0;i<size;i++){
  const uid='u'+String(i).padStart(3,'0');
  seed['users/'+uid]={plan:'pro',notificationPreferences:{pmsReminderEmail:true}};
  seed['properties/p'+uid]={uid,name:'Casa'};
  seed['bookings/b'+uid]={uid,propertyId:'p'+uid,guestName:'Test',status:'arrival',checkin:'2026-10-07',checkout:'2026-10-10',guests:1,guestRegistration:{documentsReceived:1,authorityStatus:'submitted'},cleaning:{required:false}};
 }
 return {db:new MemoryFirestore(seed),getAuthUser:async uid=>({email:uid+'@example.test',emailVerified:true}),timestamp:()=>now,now};
}
const queue=c=>queueDailyReminders(c);
function worker(c,extra={}){const mails=[];return {mails,run:()=>drainTaskNotifications({...c,pause:async()=>{},resend:{emails:{send:async payload=>{mails.push(payload);return {data:{id:'mail-'+mails.length}};}}},...extra})};}
test('default worker can send all 20 reminders generated by a full daily batch',async()=>{
 const c=setup();const q=await queue(c);assert.equal(q.queued,20);assert.equal(q.hasMore,false);
 const w=worker(c),stats=await w.run();assert.equal(stats.sent,20);assert.equal(stats.hasDueBacklog,false);assert.equal(w.mails.length,20);
 assert.equal((await w.run()).sent,0);
});
test('scanner reports remaining accounts and resets cursor at exact page end',async()=>{
 const c=setup(21);const first=await queue(c);assert.equal(first.checked,20);assert.equal(first.hasMore,true);
 assert.equal(c.db.documents.get('_pms_jobs/reminder_scan').cursor,'u019');
 const next=await queue(c);assert.equal(next.checked,1);assert.equal(next.hasMore,false);
 assert.equal(c.db.documents.get('_pms_jobs/reminder_scan').cursor,'');
 assert.equal(c.db.documents.get('_pms_jobs/reminder_scan').scanDay,'2026-10-07');
 assert.equal((await queue(c)).queued,0);
});
test('worker records bounded backlog with age and clears it after recovery',async()=>{
 const c=setup(3);await queue(c);const w=worker(c,{limit:2});
 const first=await w.run();assert.equal(first.sent,2);assert.equal(first.hasDueBacklog,true);assert.equal(first.oldestDueAt,now);assert.equal(first.needsAttention,true);
 const next=await w.run();assert.equal(next.sent,1);assert.equal(next.hasDueBacklog,false);assert.equal(next.oldestDueAt,null);
});
test('time budgets leave visible backlog and preserve scanner cursor',async()=>{
 const c=setup(3);let ticks=0;
 const stats=await queueDailyReminders({...c,clock:()=>ticks++===0?0:13000,budgetMs:12000});
 assert.equal(stats.checked,0);assert.equal(stats.budgetExhausted,true);assert.equal(stats.hasMore,true);
 await queue(c);ticks=0;const w=worker(c,{clock:()=>ticks++===0?0:21000,budgetMs:20000});
 const blocked=await w.run();assert.equal(blocked.checked,0);assert.equal(blocked.budgetExhausted,true);assert.equal(blocked.hasDueBacklog,true);
});
test('expired reminder snapshots are counted and never sent as current information',async()=>{
 const c=setup(1);await queue(c);const w=worker(c,{now:now+86400000});
 const stats=await w.run();assert.equal(stats.sent,0);assert.equal(stats.expiredReminders,1);assert.equal(stats.suppressed,1);assert.equal(stats.needsAttention,true);assert.equal(w.mails.length,0);
});
test('requested generation limit cannot silently expand daily work beyond 20 accounts',async()=>{
 const c=setup(25);const stats=await queueDailyReminders({...c,limit:10000});
 assert.equal(stats.checked,20);assert.equal(stats.hasMore,true);
});
test('bounded cleanup of 20 expired daily snapshots does not consume today\'s 20 send slots',async()=>{
 const c=setup(20);
 for(const [path,row] of c.db.documents)if(path.startsWith('bookings/'))c.db.documents.set(path,{...row,checkin:'2026-10-05'});
 await queueDailyReminders({...c,now:now-86400000});await queue(c);
 let authCalls=0;const w=worker({...c,getAuthUser:async uid=>{authCalls++;return c.getAuthUser(uid);}});
 const stats=await w.run();assert.equal(stats.expiredReminders,20);assert.equal(stats.sent,20);assert.equal(stats.checked,40);assert.equal(stats.hasDueBacklog,false);
 assert.equal(authCalls,20);assert.equal(w.mails.length,20);
});
