// ===============================================
// 💰 FINANCE KNOWLEDGE
// ===============================================

Object.assign(window.rbKnowledgeBase, {

  // ===========================================
  // ROI
  // ===========================================

  roi: {

    priority: 10,

    keywords: [
      "roi",
      "return on investment",
      "ritorno investimento",
      "rendimento",
      "investment return",
      "profitto percentuale",
      "resa investimento",
      "quanto rende",
      "redditività",
      "yield"
    ],

    aiTitleIT:
      "📈 ROI – Return On Investment",

    aiTitleEN:
      "📈 ROI – Return On Investment",

    aiSummaryIT:
      "Il ROI misura il rendimento percentuale dell’investimento rispetto al capitale investito.",

    aiSummaryEN:
      "ROI measures the percentage return generated compared to invested capital.",

    aiInsightIT:
      "Nel settore B&B e short-rent un ROI elevato può sembrare molto interessante, ma deve sempre essere analizzato insieme a cashflow, rischio operativo, occupazione reale, sostenibilità del mutuo e costi nascosti.",

    aiInsightEN:
      "In the B&B and short-rent sector, a high ROI may look attractive, but it should always be analyzed together with cashflow, operational risk, occupancy, mortgage sustainability and hidden costs.",

    warningIT:
      "⚠️ Un ROI elevato non garantisce automaticamente un investimento sicuro o sostenibile.",

    warningEN:
      "⚠️ A high ROI does not automatically guarantee a safe or sustainable investment.",

    recommendationsIT: [
      "Analizza sempre il cashflow reale.",
      "Confronta ROI e rischio operativo.",
      "Verifica occupazione e sostenibilità del mutuo."
    ],

    recommendationsEN: [
      "Always analyze real cashflow.",
      "Compare ROI with operational risk.",
      "Verify occupancy and mortgage sustainability."
    ],

    examples: [
      "ROI 8%",
      "ROI Airbnb Roma",
      "buon ROI B&B",
      "high ROI investment",
      "quanto rende un Airbnb",
      "ROI investimento immobiliare"
    ],

    related: [
      "cashflow",
      "riskScore",
      "mortgageImpact",
      "breakEven"
    ]

  },

  // ===========================================
  // CASHFLOW
  // ===========================================

  cashflow: {

    priority: 9,

    keywords: [
      "cashflow",
      "cash flow",
      "flusso cassa",
      "profitto mensile",
      "utile netto",
      "guadagno mensile",
      "monthly profit",
      "liquidità",
      "net profit"
    ],

    aiTitleIT:
      "💸 Cashflow Immobiliare",

    aiTitleEN:
      "💸 Real Estate Cashflow",

    aiSummaryIT:
      "Il Cashflow rappresenta il profitto netto reale generato ogni mese dall’investimento.",

    aiSummaryEN:
      "Cashflow represents the real monthly net profit generated by the investment.",

    aiInsightIT:
      "Il cashflow considera cleaning, utenze, manutenzione, tasse, OTA fees, gestione operativa e rata del mutuo. Un investimento può avere ROI elevato ma cashflow negativo se i costi operativi sono troppo alti.",

    aiInsightEN:
      "Cashflow includes cleaning, utilities, maintenance, taxes, OTA fees, operations and mortgage payments. An investment may show high ROI but still generate negative cashflow if operational costs are too high.",

    warningIT:
      "⚠️ ROI alto con cashflow debole può rendere l’investimento instabile nel lungo periodo.",

    warningEN:
      "⚠️ High ROI with weak cashflow may make the investment unstable long-term.",

    recommendationsIT: [
      "Riduci i costi operativi.",
      "Ottimizza occupazione e prezzo notte.",
      "Controlla la sostenibilità della rata mutuo."
    ],

    recommendationsEN: [
      "Reduce operational costs.",
      "Optimize occupancy and nightly pricing.",
      "Monitor mortgage sustainability."
    ],

    examples: [
      "cashflow negativo",
      "profitto netto Airbnb",
      "monthly cashflow",
      "utile B&B",
      "guadagno reale"
    ],

    related: [
      "roi",
      "mortgageImpact",
      "seasonality",
      "hiddenCosts"
    ]

  },

  // ===========================================
  // BREAK EVEN
  // ===========================================

  breakEven: {

    priority: 7,

    keywords: [
      "break even",
      "pareggio",
      "punto di pareggio",
      "rientro investimento",
      "tempo recupero",
      "recuperare capitale"
    ],

    aiTitleIT:
      "⚖️ Break Even",

    aiTitleEN:
      "⚖️ Break Even",

    aiSummaryIT:
      "Il Break Even indica il tempo necessario per recuperare il capitale investito.",

    aiSummaryEN:
      "Break-even indicates how long it takes to recover invested capital.",

    aiInsightIT:
      "Un break-even troppo lento aumenta l’esposizione finanziaria e il rischio operativo dell’investimento immobiliare.",

    aiInsightEN:
      "A slow break-even increases financial exposure and operational risk.",

    warningIT:
      "⚠️ Tempi di recupero troppo lunghi possono ridurre la sostenibilità finanziaria.",

    warningEN:
      "⚠️ Excessively long recovery times may reduce financial sustainability.",

    recommendationsIT: [
      "Ottimizza occupazione e ADR.",
      "Riduci costi operativi.",
      "Analizza sostenibilità cashflow."
    ],

    recommendationsEN: [
      "Optimize occupancy and ADR.",
      "Reduce operating costs.",
      "Analyze cashflow sustainability."
    ],

    examples: [
      "break even Airbnb",
      "quando recupero investimento",
      "tempo rientro capitale",
      "anni recupero investimento"
    ],

    related: [
      "roi",
      "cashflow",
      "riskScore"
    ]

  },

  // ===========================================
  // DSCR
  // ===========================================

  dscr: {

    priority: 8,

    keywords: [
      "dscr",
      "debt service coverage ratio",
      "sostenibilità mutuo",
      "copertura debito",
      "copertura rata",
      "mutuo sostenibile"
    ],

    aiTitleIT:
      "🏦 DSCR – Sostenibilità Mutuo",

    aiTitleEN:
      "🏦 DSCR – Mortgage Sustainability",

    aiSummaryIT:
      "Il DSCR misura la capacità dell’investimento di coprire la rata del mutuo tramite il cashflow generato.",

    aiSummaryEN:
      "DSCR measures the ability of the investment to cover mortgage payments using generated cashflow.",

    aiInsightIT:
      "Le banche utilizzano spesso questo parametro per valutare la sostenibilità finanziaria di un investimento immobiliare.",

    aiInsightEN:
      "Banks often use this metric to evaluate real estate investment sustainability.",

    warningIT:
      "⚠️ Un DSCR troppo basso aumenta il rischio finanziario e la possibilità di tensioni sul cashflow.",

    warningEN:
      "⚠️ A low DSCR increases financial risk and cashflow pressure.",

    recommendationsIT: [
      "Mantieni cashflow stabile.",
      "Evita rate troppo aggressive.",
      "Controlla costi operativi e occupazione."
    ],

    recommendationsEN: [
      "Maintain stable cashflow.",
      "Avoid aggressive mortgage payments.",
      "Monitor occupancy and operational costs."
    ],

    examples: [
      "DSCR 1.2",
      "mutuo sostenibile",
      "debt coverage",
      "copertura rata mutuo"
    ],

    related: [
      "mortgageImpact",
      "cashflow",
      "riskScore",
      "breakEven"
    ]

  },

  // ===========================================
  // OPERATING MARGIN
  // ===========================================

  operatingMargin: {

    priority: 6,

    keywords: [
      "margine operativo",
      "operating margin",
      "profit margin",
      "margine profitto"
    ],

    aiTitleIT:
      "📊 Margine Operativo",

    aiTitleEN:
      "📊 Operating Margin",

    aiSummaryIT:
      "Il margine operativo indica quanto profitto rimane dopo aver coperto i costi operativi.",

    aiSummaryEN:
      "Operating margin shows how much profit remains after operational expenses.",

    aiInsightIT:
      "Margini troppo bassi rendono l’investimento vulnerabile a stagionalità, aumento costi e calo occupazione.",

    aiInsightEN:
      "Low margins make investments vulnerable to seasonality, rising costs and occupancy drops.",

    warningIT:
      "⚠️ Margini ridotti aumentano il rischio operativo nel lungo periodo.",

    warningEN:
      "⚠️ Thin margins increase long-term operational risk.",

    recommendationsIT: [
      "Ottimizza pricing e occupazione.",
      "Riduci cleaning e utenze.",
      "Automatizza parte della gestione."
    ],

    recommendationsEN: [
      "Optimize pricing and occupancy.",
      "Reduce cleaning and utilities.",
      "Automate operational management."
    ],

    examples: [
      "margine Airbnb",
      "profit margin",
      "margine operativo B&B"
    ],

    related: [
      "cashflow",
      "riskScore",
      "hiddenCosts"
    ]

  }

});
