// ===============================================
// 💰 FINANCE KNOWLEDGE
// ===============================================

Object.assign(window.rbKnowledgeBase, {

  // ===========================================
  // ROI
  // ===========================================

  roi: {

    keywords: [
      "roi",
      "return on investment",
      "ritorno investimento",
      "rendimento",
      "investment return",
      "profitto percentuale",
      "resa investimento"
    ],

    answerIT:
      "Il ROI (Return on Investment) misura il rendimento percentuale dell’investimento. Un ROI elevato indica una maggiore redditività, ma deve sempre essere analizzato insieme a rischio, occupazione, cashflow e sostenibilità del mutuo.",

    answerEN:
      "ROI (Return on Investment) measures the percentage return generated by an investment. A high ROI indicates higher profitability, but it should always be evaluated together with risk, occupancy, cashflow and mortgage sustainability.",

    examples: [
      "ROI 8%",
      "ROI Airbnb Roma",
      "buon ROI B&B",
      "high ROI investment"
    ],

    related: [
      "cashflow",
      "riskScore",
      "mortgageImpact"
    ]

  },

  // ===========================================
  // CASHFLOW
  // ===========================================

  cashflow: {

    keywords: [
      "cashflow",
      "cash flow",
      "flusso cassa",
      "profitto mensile",
      "utile netto",
      "guadagno mensile",
      "monthly profit"
    ],

    answerIT:
      "Il Cashflow rappresenta il profitto netto mensile generato dall’immobile dopo aver sottratto spese operative, tasse, manutenzione e rata del mutuo. Un investimento può avere un ROI alto ma cashflow negativo.",

    answerEN:
      "Cashflow represents the monthly net profit generated after expenses, taxes, maintenance and mortgage payments. An investment may show a high ROI but still generate negative cashflow.",

    examples: [
      "cashflow negativo",
      "profitto netto Airbnb",
      "monthly cashflow",
      "utile B&B"
    ],

    related: [
      "roi",
      "mortgageImpact",
      "seasonality"
    ]

  },

  // ===========================================
  // BREAK EVEN
  // ===========================================

  breakEven: {

    keywords: [
      "break even",
      "pareggio",
      "punto di pareggio",
      "rientro investimento",
      "tempo recupero"
    ],

    answerIT:
      "Il Break Even indica il tempo necessario per recuperare l’investimento iniziale tramite i profitti generati dall’immobile.",

    answerEN:
      "Break-even indicates how long it takes to recover the initial investment through generated profits.",

    examples: [
      "break even Airbnb",
      "quando recupero investimento",
      "tempo rientro capitale"
    ],

    related: [
      "roi",
      "cashflow"
    ]

  },

  // ===========================================
  // DSCR
  // ===========================================

  dscr: {

    keywords: [
      "dscr",
      "debt service coverage ratio",
      "sostenibilità mutuo",
      "copertura debito"
    ],

    answerIT:
      "Il DSCR misura la capacità dell’investimento di coprire la rata del mutuo tramite il cashflow generato. Un DSCR troppo basso aumenta il rischio finanziario.",

    answerEN:
      "DSCR measures the ability of the investment to cover mortgage payments using generated cashflow. A low DSCR increases financial risk.",

    examples: [
      "DSCR 1.2",
      "mutuo sostenibile",
      "debt coverage"
    ],

    related: [
      "mortgageImpact",
      "cashflow",
      "riskScore"
    ]

  }

});
