// ===============================================
// 📚 GLOSSARY KNOWLEDGE
// ===============================================

Object.assign(window.rbKnowledgeBase, {

  roi:{
    type:"education",

    textIT:`
📈 ROI significa Return On Investment.

Misura quanto un investimento genera profitto rispetto al capitale investito.
`,

    textEN:`
📈 ROI means Return On Investment.

It measures investment profitability compared to invested capital.
`
  },

  cashflow:{
    type:"education",

    textIT:`
💸 Il cashflow rappresenta il flusso reale di denaro generato dall'investimento.
`,

    textEN:`
💸 Cashflow represents the real money flow generated by the investment.
`
  },

  dscr:{
    type:"education",

    textIT:`
🏦 DSCR misura la capacità dell'investimento di coprire il mutuo.
`,

    textEN:`
🏦 DSCR measures the investment ability to cover debt payments.
`
  },

  rogito:{
    type:"education",

    textIT:`
🏠 Il rogito è l'atto notarile finale della compravendita immobiliare.
`,

    textEN:`
🏠 The deed is the final notarial act of a property transaction.
`
  }

});
