// ===============================================
// 📚 GLOSSARY KNOWLEDGE
// ===============================================

Object.assign(window.rbKnowledgeBase, {

  roi:{

    type:"education",

    priority:10,

    keywords:[
      "roi",
      "return on investment",
      "rendimento",
      "profitto investimento"
    ],

    aiTitleIT:"📈 ROI — RETURN ON INVESTMENT",
    aiTitleEN:"📈 ROI — RETURN ON INVESTMENT",

    aiSummaryIT:`
ROI significa Return On Investment.
`,

    aiSummaryEN:`
ROI means Return On Investment.
`,

    aiInsightIT:`
📊 Misura quanto un investimento genera profitto rispetto al capitale investito.

Formula semplificata:

ROI = profitto netto / investimento totale × 100

💡 Un ROI elevato può indicare maggiore redditività ma anche maggiore rischio operativo.
`,

    aiInsightEN:`
📊 It measures how profitable an investment is compared to invested capital.

Simple formula:

ROI = net profit / total investment × 100

💡 Higher ROI may indicate higher profitability but also higher operational risk.
`,

    recommendationsIT:[
      "Analizza sempre ROI insieme al cashflow",
      "Valuta rischio e sostenibilità oltre il rendimento"
    ],

    recommendationsEN:[
      "Always analyze ROI together with cashflow",
      "Evaluate risk and sustainability beyond profitability"
    ]

  },

  cashflow:{

    type:"education",

    priority:10,

    keywords:[
      "cashflow",
      "cash flow",
      "flusso di cassa",
      "liquidità"
    ],

    aiTitleIT:"💸 CASHFLOW",
    aiTitleEN:"💸 CASHFLOW",

    aiSummaryIT:`
Il cashflow rappresenta il flusso reale di denaro generato dall'investimento.
`,

    aiSummaryEN:`
Cashflow represents the real money flow generated by the investment.
`,

    aiInsightIT:`
📊 Formula semplificata:

Entrate - uscite = cashflow

Include:

• affitti
• mutuo
• tasse
• manutenzione
• gestione

💡 Cashflow positivo migliora sostenibilità e sicurezza finanziaria.
`,

    aiInsightEN:`
📊 Simple formula:

Income - expenses = cashflow

Includes:

• rents
• mortgage
• taxes
• maintenance
• management

💡 Positive cashflow improves sustainability and financial stability.
`,

    recommendationsIT:[
      "Calcola sempre cashflow netto reale",
      "Considera costi nascosti e tasse"
    ],

    recommendationsEN:[
      "Always calculate real net cashflow",
      "Consider hidden costs and taxes"
    ]

  },

  dscr:{

    type:"education",

    priority:9,

    keywords:[
      "dscr",
      "debt service coverage ratio",
      "sostenibilità mutuo"
    ],

    aiTitleIT:"🏦 DSCR",
    aiTitleEN:"🏦 DSCR",

    aiSummaryIT:`
DSCR misura la capacità dell'investimento di coprire il mutuo.
`,

    aiSummaryEN:`
DSCR measures the investment ability to cover debt payments.
`,

    aiInsightIT:`
📊 Formula semplificata:

DSCR = cashflow operativo / rata debito

Generalmente:

• sopra 1.2 → sostenibile
• sotto 1 → rischio elevato

💡 Il DSCR è fondamentale per valutare sostenibilità finanziaria.
`,

    aiInsightEN:`
📊 Simple formula:

DSCR = operating cashflow / debt payments

Generally:

• above 1.2 → sustainable
• below 1 → high risk

💡 DSCR is critical for evaluating financial sustainability.
`,

    recommendationsIT:[
      "Valuta DSCR prima di accendere un mutuo",
      "Monitora sostenibilità del debito"
    ],

    recommendationsEN:[
      "Evaluate DSCR before taking a mortgage",
      "Monitor debt sustainability carefully"
    ]

  },

  rogito:{

    type:"education",

    priority:8,

    keywords:[
      "rogito",
      "atto notarile",
      "deed",
      "property deed"
    ],

    aiTitleIT:"🏠 ROGITO IMMOBILIARE",
    aiTitleEN:"🏠 PROPERTY DEED",

    aiSummaryIT:`
Il rogito è l'atto notarile finale della compravendita immobiliare.
`,

    aiSummaryEN:`
The deed is the final notarial act of a property transaction.
`,

    aiInsightIT:`
📄 Generalmente include:

• trasferimento proprietà
• pagamento finale
• verifica documentazione
• registrazione ufficiale

💡 Il rogito conclude legalmente l'acquisto dell'immobile.
`,

    aiInsightEN:`
📄 Generally includes:

• property transfer
• final payment
• document verification
• official registration

💡 The deed legally finalizes the property purchase.
`,

    recommendationsIT:[
      "Verifica documentazione immobile prima del rogito",
      "Considera costi notarili e fiscali"
    ],

    recommendationsEN:[
      "Verify property documentation before closing",
      "Consider notary and tax costs"
    ]

  }

});
