// ===============================================
// 📚 GLOSSARY KNOWLEDGE
// ===============================================

Object.assign(window.rbKnowledgeBase, {

  roi:{

    type:"education",

    keywords:[
      "roi",
      "return on investment",
      "rendimento",
      "profitto investimento"
    ],

    textIT:`
📈 ROI significa Return On Investment.

Misura quanto un investimento genera profitto rispetto al capitale investito.

💡 Un ROI elevato può indicare maggiore redditività ma anche maggiore rischio operativo.
`,

    textEN:`
📈 ROI means Return On Investment.

It measures how profitable an investment is compared to invested capital.

💡 Higher ROI may indicate higher profitability but also higher operational risk.
`

  },

  cashflow:{

    type:"education",

    keywords:[
      "cashflow",
      "cash flow",
      "flusso di cassa",
      "liquidità"
    ],

    textIT:`
💸 Il cashflow rappresenta il flusso reale di denaro generato dall'investimento.

Entrate - uscite = cashflow.
`,

    textEN:`
💸 Cashflow represents the real money flow generated by the investment.

Income - expenses = cashflow.
`

  },

  dscr:{

    type:"education",

    keywords:[
      "dscr",
      "debt service coverage ratio",
      "sostenibilità mutuo"
    ],

    textIT:`
🏦 DSCR misura la capacità dell'investimento di coprire il mutuo.

📊 Sopra 1.2 è generalmente sostenibile.
`,

    textEN:`
🏦 DSCR measures the investment ability to cover debt payments.

📊 Above 1.2 is generally considered sustainable.
`

  },

  rogito:{

    type:"education",

    keywords:[
      "rogito",
      "atto notarile",
      "deed",
      "property deed"
    ],

    textIT:`
🏠 Il rogito è l'atto notarile finale della compravendita immobiliare.
`,

    textEN:`
🏠 The deed is the final notarial act of a property transaction.
`

  }

});
