// ===============================================
// RENDIMENTOBB – AI KNOWLEDGE BASE PRO
// Silicon Valley SaaS Educational Engine
// ===============================================

window.rbKnowledgeBase = {

// ===========================================
// ROI
// ===========================================

roi: {

  keywords: [
    "roi",
    "rendimento",
    "return on investment"
  ],

  priority: 10,

premium: false,

version: "1.0",

searchWeight: 10,

relatedQuestions: [
  "cashflow",
  "breakEven",
  "occupancy",
  "dscr",
  "mortgageImpact",
  "riskScore"
],

recommendationsIT: [
  "Analizza anche il cashflow reale",
  "Controlla il DSCR prima di investire",
  "Verifica il break-even dell'immobile",
  "Analizza il rischio operativo reale"
],

recommendationsEN: [
  "Analyze real cashflow as well",
  "Check DSCR before investing",
  "Review property break-even",
  "Analyze real operational risk"
],

  category: "profitability",

  importance: "critical",

  riskLevel: "medium",

  benchmark: "8-10%",

  relatedMetrics: [
    "cashflow",
    "breakEven",
    "occupancy",
    "dscr"
  ],

  aiTitleIT: "📈 ROI – Return On Investment",

  aiTitleEN: "📈 ROI – Return On Investment",

  aiSummaryIT: `
Il ROI misura la redditività dell'investimento rispetto al capitale investito.

Nel mercato short rent il ROI è uno degli indicatori principali per valutare la sostenibilità economica di un immobile.

💡 Benchmark settore:
un ROI superiore all'8-10% viene generalmente considerato molto competitivo nel mercato B&B.
`,

  aiSummaryEN: `
ROI measures investment profitability compared to invested capital.

In the short rental market, ROI is one of the main indicators used to evaluate property sustainability.

💡 Industry benchmark:
ROI above 8-10% is generally considered very competitive in the B&B market.
`,

  aiInsightIT: `
💡 AI Insight:
un ROI elevato non garantisce automaticamente un investimento sicuro.

Cashflow, rischio operativo, mutuo e stagionalità possono ridurre drasticamente la redditività reale.
`,

  aiInsightEN: `
💡 AI Insight:
high ROI does not automatically guarantee a safe investment.

Cashflow, operational risk, mortgage exposure and seasonality may drastically reduce real profitability.
`,

  warningIT: `
⚠️ ROI molto elevati possono indicare stime troppo ottimistiche o rischio operativo maggiore.
`,

  warningEN: `
⚠️ Extremely high ROI projections may indicate unrealistic assumptions or elevated operational risk.
`

},
// ===========================================
// CASHFLOW
// ===========================================

cashflow: {

  keywords: [
    "cashflow",
    "cash flow",
    "flusso di cassa"
  ],

  priority: 9,

premium: false,

version: "1.0",

searchWeight: 9,

relatedQuestions: [
  "roi",
  "dscr",
  "breakEven",
  "mortgageImpact",
  "financialSustainability"
],

recommendationsIT: [
  "Verifica la sostenibilità del mutuo",
  "Analizza il DSCR dell'investimento",
  "Controlla il break-even reale",
  "Riduci i costi operativi"
],

recommendationsEN: [
  "Review mortgage sustainability",
  "Analyze investment DSCR",
  "Check real break-even",
  "Reduce operational costs"
],

  category: "financial-sustainability",

  importance: "critical",

  riskLevel: "high",

  benchmark: "positivo e stabile",

  relatedMetrics: [
    "roi",
    "dscr",
    "breakEven",
    "mortgageImpact"
  ],

  aiTitleIT: "💸 Cashflow – Liquidità reale",

  aiTitleEN: "💸 Cashflow – Real liquidity",

  aiSummaryIT: `
Il cashflow rappresenta la liquidità reale generata dall'investimento dopo tutte le spese operative.

Include costi come:

• utenze
• cleaning
• manutenzione
• tasse
• commissioni OTA
• eventuale mutuo

Un cashflow positivo indica che l'immobile genera liquidità sostenibile nel tempo.
`,

  aiSummaryEN: `
Cashflow represents the real liquidity generated by the investment after all operating expenses.

Includes costs such as:

• utilities
• cleaning
• maintenance
• taxes
• OTA commissions
• mortgage payments

Positive cashflow indicates the property generates sustainable long-term liquidity.
`,

  aiInsightIT: `
💡 AI Insight:
molti investimenti mostrano ROI elevati ma cashflow molto basso o negativo.

Questo può creare problemi di sostenibilità finanziaria anche con occupazione elevata.
`,

  aiInsightEN: `
💡 AI Insight:
many investments show high ROI but weak or even negative cashflow.

This may create financial sustainability issues even with high occupancy.
`,

  warningIT: `
⚠️ Un cashflow negativo aumenta significativamente il rischio operativo dell'investimento.
`,

  warningEN: `
⚠️ Negative cashflow significantly increases operational investment risk.
`

},

// ===========================================
// OCCUPANCY
// ===========================================

occupancy: {

  keywords: [
    "occupazione",
    "occupancy",
    "booking rate",
    "tasso occupazione"
  ],

  category: "market-performance",

  importance: "high",

  riskLevel: "medium",

  benchmark: "65-70%",

  relatedMetrics: [
    "roi",
    "cashflow",
    "seasonality",
    "marketDemand"
  ],

  aiTitleIT: "🏨 Occupazione – Tasso prenotazioni",

  aiTitleEN: "🏨 Occupancy – Booking rate",

  aiSummaryIT: `
L'occupazione rappresenta la percentuale di notti prenotate durante l'anno.

Nel settore short rent è uno degli indicatori più importanti per stimare sostenibilità e redditività reale.

💡 Benchmark settore:
un'occupazione superiore al 65-70% viene generalmente considerata molto positiva.
`,

  aiSummaryEN: `
Occupancy represents the percentage of booked nights throughout the year.

In the short rental sector it is one of the most important indicators for estimating sustainability and real profitability.

💡 Industry benchmark:
occupancy above 65-70% is generally considered very strong.
`,

  aiInsightIT: `
💡 AI Insight:
un'occupazione elevata può compensare ROI più bassi e migliorare la stabilità del cashflow.

Le città con forte domanda turistica e business tendono a mantenere occupazione più stabile durante l'anno.
`,

  aiInsightEN: `
💡 AI Insight:
high occupancy may compensate lower ROI and improve cashflow stability.

Cities with strong tourism and business demand tend to maintain more stable occupancy throughout the year.
`,

  warningIT: `
⚠️ Occupazioni troppo elevate potrebbero indicare stime irrealistiche o forte esposizione stagionale.
`,

  warningEN: `
⚠️ Extremely high occupancy assumptions may indicate unrealistic projections or strong seasonal exposure.
`

},

// ===========================================
// BREAK EVEN
// ===========================================

breakEven: {

  keywords: [
    "break even",
    "pareggio",
    "punto di pareggio"
  ],

  category: "financial-risk",

  importance: "critical",

  riskLevel: "high",

  benchmark: "6-9 anni",

  relatedMetrics: [
    "roi",
    "cashflow",
    "dscr",
    "mortgageImpact"
  ],

  aiTitleIT: "⚖️ Break-even – Recupero investimento",

  aiTitleEN: "⚖️ Break-even – Investment recovery",

  aiSummaryIT: `
Il break-even rappresenta il tempo necessario per recuperare l'investimento iniziale attraverso i profitti generati dall'immobile.

Nel settore B&B è uno degli indicatori principali per valutare sostenibilità e rischio finanziario.

💡 Benchmark settore:
un break-even inferiore a 6-9 anni viene generalmente considerato competitivo.
`,

  aiSummaryEN: `
Break-even represents the time required to recover the initial investment through the property's generated profits.

In the B&B sector it is one of the main indicators used to evaluate sustainability and financial risk.

💡 Industry benchmark:
break-even below 6-9 years is generally considered competitive.
`,

  aiInsightIT: `
💡 AI Insight:
break-even più rapidi riducono l'esposizione finanziaria e aumentano la resilienza dell'investimento.

Immobili con ROI elevato ma break-even troppo lungo possono nascondere rischio operativo maggiore.
`,

  aiInsightEN: `
💡 AI Insight:
faster break-even reduces financial exposure and improves investment resilience.

Properties with high ROI but excessively long break-even periods may hide elevated operational risk.
`,

  warningIT: `
⚠️ Break-even troppo elevati aumentano rischio finanziario, esposizione al mercato e vulnerabilità operativa.
`,

  warningEN: `
⚠️ Extremely long break-even periods increase financial risk, market exposure and operational vulnerability.
`

},
// ===========================================
// DSCR
// ===========================================

dscr: {

  keywords: [
    "dscr",
    "debt service coverage ratio",
    "copertura mutuo"
  ],

  category: "financial-sustainability",

  importance: "critical",

  riskLevel: "high",

  benchmark: "1.2+",

  relatedMetrics: [
    "cashflow",
    "breakEven",
    "mortgageImpact",
    "roi"
  ],

  aiTitleIT: "🏦 DSCR – Sostenibilità mutuo",

  aiTitleEN: "🏦 DSCR – Mortgage sustainability",

  aiSummaryIT: `
Il DSCR (Debt Service Coverage Ratio) misura la capacità dell'investimento di sostenere il mutuo attraverso i ricavi generati dall'immobile.

È uno degli indicatori più utilizzati da banche e investitori professionali per valutare sostenibilità finanziaria e rischio credito.

💡 Benchmark bancario:
un DSCR superiore a 1.2 viene generalmente considerato sano.
`,

  aiSummaryEN: `
DSCR (Debt Service Coverage Ratio) measures the investment’s ability to sustain mortgage debt using the income generated by the property.

It is one of the most widely used metrics by banks and professional investors to evaluate financial sustainability and credit risk.

💡 Banking benchmark:
a DSCR above 1.2 is generally considered healthy.
`,

  aiInsightIT: `
💡 AI Insight:
un DSCR elevato aumenta la resilienza dell'investimento durante periodi di bassa occupazione o riduzione dei ricavi.

Molti investimenti apparentemente profittevoli diventano fragili quando il DSCR scende sotto livelli sostenibili.
`,

  aiInsightEN: `
💡 AI Insight:
high DSCR improves investment resilience during low occupancy periods or revenue declines.

Many apparently profitable investments become financially fragile when DSCR falls below sustainable levels.
`,

  warningIT: `
⚠️ Un DSCR troppo basso indica rischio finanziario elevato e possibile difficoltà nel sostenere il mutuo.
`,

  warningEN: `
⚠️ Low DSCR values indicate elevated financial risk and potential difficulty sustaining mortgage payments.
`

},

// ===========================================
// RISK SCORE
// ===========================================

riskScore: {

  keywords: [
    "risk",
    "risk score",
    "rischio",
    "rischio investimento"
  ],

  category: "risk-analysis",

  importance: "critical",

  riskLevel: "high",

  benchmark: "basso-moderato",

  relatedMetrics: [
    "roi",
    "cashflow",
    "breakEven",
    "dscr"
  ],

  aiTitleIT: "⚠️ Risk Score – Rischio investimento",

  aiTitleEN: "⚠️ Risk Score – Investment risk",

  aiSummaryIT: `
Il Risk Score misura il livello di rischio operativo e finanziario dell'investimento.

L'analisi considera sostenibilità economica, mutuo, cashflow, occupazione e resilienza del mercato.
`,

  aiSummaryEN: `
Risk Score measures the operational and financial risk level of the investment.

The analysis considers economic sustainability, mortgage exposure, cashflow, occupancy and market resilience.
`,

  aiInsightIT: `
💡 AI Insight:
investimenti con ROI elevato possono comunque presentare rischio operativo molto alto.

La sostenibilità reale dipende dall'equilibrio tra profitto, liquidità e stabilità mercato.
`,

  aiInsightEN: `
💡 AI Insight:
investments with high ROI may still carry elevated operational risk.

Real sustainability depends on the balance between profitability, liquidity and market stability.
`,

  warningIT: `
⚠️ Rischio elevato può aumentare volatilità e possibilità di perdita reale nel lungo periodo.
`,

  warningEN: `
⚠️ High risk may increase volatility and long-term loss exposure.
`

},

// ===========================================
// MARKET DEMAND
// ===========================================

marketDemand: {

  keywords: [
    "domanda",
    "market demand",
    "richiesta mercato"
  ],

  category: "market-analysis",

  importance: "high",

  riskLevel: "medium",

  benchmark: "alta domanda stabile",

  relatedMetrics: [
    "occupancy",
    "cashflow",
    "seasonality"
  ],

  aiTitleIT: "📊 Domanda mercato",

  aiTitleEN: "📊 Market demand",

  aiSummaryIT: `
La domanda di mercato misura l'interesse reale verso affitti brevi e strutture ricettive in una specifica città o area.

Una domanda elevata migliora occupazione, stabilità e sostenibilità del cashflow.
`,

  aiSummaryEN: `
Market demand measures real interest toward short rentals and hospitality properties within a specific city or area.

Strong demand improves occupancy, stability and cashflow sustainability.
`,

  aiInsightIT: `
💡 AI Insight:
mercati con domanda stabile tendono a mantenere performance migliori anche durante periodi economici più deboli.
`,

  aiInsightEN: `
💡 AI Insight:
markets with stable demand tend to maintain stronger performance even during weaker economic periods.
`,

  warningIT: `
⚠️ Domanda debole o instabile aumenta il rischio operativo e la volatilità dell'investimento.
`,

  warningEN: `
⚠️ Weak or unstable demand increases operational risk and investment volatility.
`

},

// ===========================================
// SEASONALITY
// ===========================================

seasonality: {

  keywords: [
    "stagionalità",
    "seasonality",
    "alta stagione",
    "bassa stagione"
  ],

  category: "market-risk",

  importance: "high",

  riskLevel: "medium",

  benchmark: "stagionalità moderata",

  relatedMetrics: [
    "occupancy",
    "cashflow",
    "marketDemand"
  ],

  aiTitleIT: "🌍 Stagionalità mercato",

  aiTitleEN: "🌍 Market seasonality",

  aiSummaryIT: `
La stagionalità misura quanto il mercato dipende da specifici periodi dell'anno.

Mercati troppo stagionali possono creare forti variazioni di occupazione e cashflow.
`,

  aiSummaryEN: `
Seasonality measures how much the market depends on specific periods of the year.

Highly seasonal markets may create significant occupancy and cashflow fluctuations.
`,

  aiInsightIT: `
💡 AI Insight:
città con domanda business o turismo internazionale tendono ad avere stagionalità più stabile.
`,

  aiInsightEN: `
💡 AI Insight:
cities with business demand or international tourism generally maintain more stable seasonality.
`,

  warningIT: `
⚠️ Elevata stagionalità può aumentare rischio operativo e instabilità finanziaria.
`,

  warningEN: `
⚠️ High seasonality may increase operational risk and financial instability.
`

},

// ===========================================
// PROPERTY SCORE
// ===========================================

propertyScore: {

  keywords: [
    "property score",
    "score immobile",
    "investment score"
  ],

  category: "investment-analysis",

  importance: "high",

  riskLevel: "medium",

  benchmark: "A-B",

  relatedMetrics: [
    "roi",
    "cashflow",
    "riskScore",
    "occupancy"
  ],

  aiTitleIT: "🏠 Property Score – Valutazione investimento",

  aiTitleEN: "🏠 Property Score – Investment rating",

  aiSummaryIT: `
Il Property Score rappresenta una valutazione complessiva dell'investimento basata su redditività, rischio e sostenibilità.

Il sistema utilizza metriche finanziarie e benchmark di mercato per stimare la qualità dell'operazione.
`,

  aiSummaryEN: `
Property Score represents an overall investment evaluation based on profitability, risk and sustainability.

The system uses financial metrics and market benchmarks to estimate investment quality.
`,

  aiInsightIT: `
💡 AI Insight:
un investimento equilibrato tende a mantenere score più stabili anche durante variazioni mercato.
`,

  aiInsightEN: `
💡 AI Insight:
balanced investments tend to maintain more stable scores during market fluctuations.
`,

  warningIT: `
⚠️ Score bassi possono indicare criticità operative o sostenibilità finanziaria debole.
`,

  warningEN: `
⚠️ Low scores may indicate operational weaknesses or poor financial sustainability.
`

},

// ===========================================
// MORTGAGE IMPACT
// ===========================================

mortgageImpact: {

  keywords: [
    "mutuo",
    "mortgage",
    "loan",
    "finanziamento"
  ],

  category: "financial-risk",

  importance: "critical",

  riskLevel: "high",

  benchmark: "sostenibile",

  relatedMetrics: [
    "cashflow",
    "dscr",
    "breakEven",
    "roi"
  ],

  aiTitleIT: "🏦 Impatto mutuo",

  aiTitleEN: "🏦 Mortgage impact",

  aiSummaryIT: `
Il mutuo può ridurre significativamente il cashflow reale dell'investimento.

Molti immobili con ROI positivo diventano meno sostenibili dopo il finanziamento.
`,

  aiSummaryEN: `
Mortgage exposure may significantly reduce real investment cashflow.

Many properties with positive ROI become financially weaker after financing.
`,

  aiInsightIT: `
💡 AI Insight:
il rapporto tra rata mensile, occupazione e cashflow è uno degli indicatori più critici nel settore short rent.
`,

  aiInsightEN: `
💡 AI Insight:
the relationship between loan payments, occupancy and cashflow is one of the most critical indicators in the short rental sector.
`,

  warningIT: `
⚠️ Mutui troppo aggressivi aumentano rischio operativo e vulnerabilità finanziaria.
`,

  warningEN: `
⚠️ Aggressive mortgage structures increase operational and financial risk.
`

},

// ===========================================
// FINANCIAL SUSTAINABILITY
// ===========================================

financialSustainability: {

  keywords: [
    "sostenibilità",
    "financial sustainability",
    "sostenibilità finanziaria"
  ],

  category: "financial-analysis",

  importance: "critical",

  riskLevel: "medium",

  benchmark: "stabile",

  relatedMetrics: [
    "cashflow",
    "dscr",
    "breakEven",
    "riskScore"
  ],

  aiTitleIT: "🧠 Sostenibilità finanziaria",

  aiTitleEN: "🧠 Financial sustainability",

  aiSummaryIT: `
La sostenibilità finanziaria misura la capacità dell'investimento di mantenere stabilità economica nel lungo periodo.

L'analisi considera cashflow, rischio, mutuo e resilienza del mercato.
`,

  aiSummaryEN: `
Financial sustainability measures the investment’s ability to maintain long-term economic stability.

The analysis considers cashflow, risk, mortgage exposure and market resilience.
`,

  aiInsightIT: `
💡 AI Insight:
investimenti sostenibili tendono a resistere meglio a crisi mercato, cali occupazione e aumento costi operativi.
`,

  aiInsightEN: `
💡 AI Insight:
sustainable investments tend to better withstand market crises, occupancy declines and rising operating costs.
`,

  warningIT: `
⚠️ Bassa sostenibilità finanziaria aumenta il rischio di perdita reale nel lungo periodo.
`,

  warningEN: `
⚠️ Weak financial sustainability increases long-term real loss risk.
`

}

};
